language: go
sudo: false

arch:
  - amd64
  - ppc64le

go_import_path: github.com/ncw/swift

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

matrix:
  include:
  - go: 1.15.x
    env: TEST_REAL_SERVER=rackspace
  - go: 1.15.x
    env: TEST_REAL_SERVER=memset
  - go: 1.15.x
    arch: ppc64le
    env: TEST_REAL_SERVER=rackspace
  - go: 1.15.x
    arch: ppc64le
    env: TEST_REAL_SERVER=memset
  allow_failures:
  - go: 1.15.x
    env: TEST_REAL_SERVER=rackspace
  - go: 1.15.x
    env: TEST_REAL_SERVER=memset
  - go: 1.15.x
    arch: ppc64le
    env: TEST_REAL_SERVER=rackspace
  - go: 1.15.x
    arch: ppc64le
    env: TEST_REAL_SERVER=memset
install: go test -i ./...
script:
  - test -z "$(go fmt ./...)"
  - go test
  - ./travis_realserver.sh
